2023-08-24 08:19:25,787 (61957/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:19:25,787 (61957/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:19:25,792 (61957/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "john" does not exist\n'
2023-08-24 08:19:33,523 (62063/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:19:33,523 (62063/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:20:11,265 (62063/MainThread) pgcli.pgexecute ERROR - sql: 'select * instacart.company_employeev2 limi', error: SyntaxError('syntax error at or near "instacart"\nLINE 1: select * instacart.company_employeev2 limi\n                 ^')
2023-08-24 08:20:11,266 (62063/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "instacart"\nLINE 1: select * instacart.company_employeev2 limi\n                 ^\n'
2023-08-24 08:20:15,965 (62063/MainThread) pgcli.pgexecute ERROR - sql: 'select * instacart.company_employeev2 limit 1', error: SyntaxError('syntax error at or near "instacart"\nLINE 1: select * instacart.company_employeev2 limit 1\n                 ^')
2023-08-24 08:20:15,966 (62063/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "instacart"\nLINE 1: select * instacart.company_employeev2 limit 1\n                 ^\n'
2023-08-24 08:23:09,749 (62387/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:23:09,749 (62387/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:26:01,179 (62639/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:26:01,179 (62639/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:26:10,071 (62769/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:26:10,071 (62769/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:26:54,052 (63007/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:26:54,052 (63007/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:27:28,849 (63164/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:27:28,849 (63164/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:29:22,680 (63361/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:29:22,681 (63361/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:29:48,896 (63451/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:29:48,896 (63451/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-24 08:31:33,212 (63637/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-08-24 08:31:33,212 (63637/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-05 13:14:01,847 (944/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-11-05 13:14:01,848 (944/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-30 17:22:54,569 (23237/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-11-30 17:22:54,569 (23237/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-30 17:23:40,210 (23569/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-11-30 17:23:40,211 (23569/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-30 17:23:47,283 (23569/MainThread) pgcli.pgexecute ERROR - sql: 'drop schema canva', error: DependentObjectsStillExist('cannot drop schema canva because other objects depend on it\nDETAIL:  function canva._add_ccp_discretionaryfund_to_descendant_paths() depends on schema canva\nfunction canva._delete_ccp_discretionaryfund() depends on schema canva\nfunction canva._update_ccp_discretionaryfund_descendant_paths() depends on schema canva\nfunction canva._update_ccp_discretionaryfund_path() depends on schema canva\ntable canva.approval_chains_approvalchain depends on schema canva\ntable canva.approval_chains_chainmatcher depends on schema canva\ntable canva.approval_chains_link depends on schema canva\ntable canva.approval_chains_linkapprover depends on schema canva\ntable canva.ats_ats depends on schema canva\ntable canva.ats_atsmappingoptions depends on schema canva\ntable canva.ats_ghcandidate depends on schema canva\ntable canva.ats_ghcustomfield depends on schema canva\ntable canva.ats_ghcustomfieldgroup depends on schema canva\ntable canva.ats_ghcustomfieldoption depends on schema canva\ntable canva.ats_ghjob depends on schema canva\ntable canva.ats_ghoffer depends on schema canva\ntable canva.ats_ghshowif depends on schema canva\ntable canva.ats_greenhousemapping depends on schema canva\ntable canva.ats_integrationrecord depends on schema canva\ntable canva.auth_group depends on schema canva\ntable canva.auth_group_permissions depends on schema canva\ntable canva.auth_permission depends on schema canva\ntable canva.authtoken_token depends on schema canva\ntable canva.ccp_ccpemployee depends on schema canva\ntable canva.ccp_ccpemployeeactivity depends on schema canva\ntable canva.ccp_ccpemployeeactivity_mentions depends on schema canva\ntable canva.ccp_ccpemployeechangehistory depends on schema canva\ntable canva.ccp_compcycle depends on schema canva\ntable canva.ccp_compelement depends on schema canva\ntable canva.ccp_computation depends on schema canva\ntable canva.ccp_computation_employees depends on schema canva\ntable canva.ccp_computationchangehistory depends on schema canva\ntable canva.ccp_csvexport depends on schema canva\ntable canva.ccp_csvimport depends on schema canva\ntable canva.ccp_csvimportemployeepatch depends on schema canva\ntable canva.ccp_dataoption depends on schema canva\ntable canva.ccp_discretionaryfund depends on schema canva\ntable canva.ccp_displaydata depends on schema canva\ntable canva.ccp_displaylayout depends on schema canva\ntable canva.ccp_planninggroup depends on schema canva\ntable canva.ccp_planninggroupchangehistory depends on schema canva\ntable canva.ccp_planningrole depends on schema canva\ntable canva.ccp_planningrole_ccp_employees depends on schema canva\ntable canva.ccp_planningrole_users depends on schema canva\ntable canva.ccp_rewardletter depends on schema canva\ntable canva.ccp_rewardletterarchive depends on schema canva\ntable canva.ccp_rewardletterconfig depends on schema canva\ntable canva.ccp_rewardletterimport depends on schema canva\ntable canva.ccp_wave depends on schema canva\ntable canva.colav2_colav2 depends on schema canva\ntable canva.colav2_colav2compensation depends on schema canva\ntable canva.colav2_colav2culturecontent depends on schema canva\ntable canva.colav2_colav2settings depends on schema canva\ntable canva.colav2_compensationequity depends on schema canva\ntable canva.colav2_visualofferbenefit depends on schema canva\ntable canva.colav2_visualoffergeneralsettings depends on schema canva\ntable canva.company_bulkimport depends on schema canva\ntable canva.company_candidate depends on schema canva\ntable canva.company_company depends on schema canva\ntable canva.company_companydepartment depends on schema canva\ntable canva.company_companyrange depends on schema canva\ntable canva.company_country depends on schema canva\ntable canva.company_ecoheaderconfig depends on schema canva\ntable canva.company_employee depends on schema canva\ntable canva.company_employeev2 depends on schema canva\ntable canva.company_employeev2csvimport depends on schema canva\ntable canva.company_employeev2displaydata depends on schema canva\ntable canva.company_employeev2displaylayout depends on schema canva\ntable canva.company_employeev2optiongrant depends on schema canva\ntable canva.company_employeev2optiongrantcsvimport depends on schema canva\ntable canva.company_employeev2vestingschedule depends on schema canva\ntable canva.company_employeev2vestingschedulecsvimport depends on schema canva\ntable canva.company_employeev2vestingschedulerow depends on schema canva\ntable canva.company_geo depends on schema canva\ntable canva.company_idp depends on schema canva\ntable canva.company_job depends on schema canva\ntable canva.company_jobrole depends on schema canva\ntable canva.company_level depends on schema canva\ntable canva.company_pbeconfig depends on schema canva\ntable canva.company_region depends on schema canva\ntable canva.company_ssosettings depends on schema canva\ntable canva.company_tablerow depends on schema canva\ntable canva.company_tablerow_calculated_from depends on schema canva\ntable canva.company_tablerow_range_calculated_from depends on schema canva\ntable canva.company_team depends on schema canva\ntable canva.csvimport_csvimport depends on schema canva\ntable canva.csvimport_importmodel depends on schema canva\ntable canva.csvtests_country depends on schema canva\ntable canva.csvtests_issue98 depends on schema canva\ntable canva.csvtests_item depends on schema canva\ntable canva.csvtests_organisation depends on schema canva\ntable canva.csvtests_unitofmeasure depends on schema canva\ntable canva.defender_accessattempt depends on schema canva\ntable canva.django_admin_log depends on schema canva\ntable canva.django_content_type depends on schema canva\ntable canva.django_migrations depends on schema canva\ntable canva.django_rest_passwordreset_resetpasswordtoken depends on schema canva\ntable canva.django_session depends on schema canva\ntable canva.django_site depends on schema canva\ntable canva.file_file depends on schema canva\nand 110 other objects (see server log for list)\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.')
2023-11-30 17:23:47,286 (23569/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DependentObjectsStillExist: cannot drop schema canva because other objects depend on it\nDETAIL:  function canva._add_ccp_discretionaryfund_to_descendant_paths() depends on schema canva\nfunction canva._delete_ccp_discretionaryfund() depends on schema canva\nfunction canva._update_ccp_discretionaryfund_descendant_paths() depends on schema canva\nfunction canva._update_ccp_discretionaryfund_path() depends on schema canva\ntable canva.approval_chains_approvalchain depends on schema canva\ntable canva.approval_chains_chainmatcher depends on schema canva\ntable canva.approval_chains_link depends on schema canva\ntable canva.approval_chains_linkapprover depends on schema canva\ntable canva.ats_ats depends on schema canva\ntable canva.ats_atsmappingoptions depends on schema canva\ntable canva.ats_ghcandidate depends on schema canva\ntable canva.ats_ghcustomfield depends on schema canva\ntable canva.ats_ghcustomfieldgroup depends on schema canva\ntable canva.ats_ghcustomfieldoption depends on schema canva\ntable canva.ats_ghjob depends on schema canva\ntable canva.ats_ghoffer depends on schema canva\ntable canva.ats_ghshowif depends on schema canva\ntable canva.ats_greenhousemapping depends on schema canva\ntable canva.ats_integrationrecord depends on schema canva\ntable canva.auth_group depends on schema canva\ntable canva.auth_group_permissions depends on schema canva\ntable canva.auth_permission depends on schema canva\ntable canva.authtoken_token depends on schema canva\ntable canva.ccp_ccpemployee depends on schema canva\ntable canva.ccp_ccpemployeeactivity depends on schema canva\ntable canva.ccp_ccpemployeeactivity_mentions depends on schema canva\ntable canva.ccp_ccpemployeechangehistory depends on schema canva\ntable canva.ccp_compcycle depends on schema canva\ntable canva.ccp_compelement depends on schema canva\ntable canva.ccp_computation depends on schema canva\ntable canva.ccp_computation_employees depends on schema canva\ntable canva.ccp_computationchangehistory depends on schema canva\ntable canva.ccp_csvexport depends on schema canva\ntable canva.ccp_csvimport depends on schema canva\ntable canva.ccp_csvimportemployeepatch depends on schema canva\ntable canva.ccp_dataoption depends on schema canva\ntable canva.ccp_discretionaryfund depends on schema canva\ntable canva.ccp_displaydata depends on schema canva\ntable canva.ccp_displaylayout depends on schema canva\ntable canva.ccp_planninggroup depends on schema canva\ntable canva.ccp_planninggroupchangehistory depends on schema canva\ntable canva.ccp_planningrole depends on schema canva\ntable canva.ccp_planningrole_ccp_employees depends on schema canva\ntable canva.ccp_planningrole_users depends on schema canva\ntable canva.ccp_rewardletter depends on schema canva\ntable canva.ccp_rewardletterarchive depends on schema canva\ntable canva.ccp_rewardletterconfig depends on schema canva\ntable canva.ccp_rewardletterimport depends on schema canva\ntable canva.ccp_wave depends on schema canva\ntable canva.colav2_colav2 depends on schema canva\ntable canva.colav2_colav2compensation depends on schema canva\ntable canva.colav2_colav2culturecontent depends on schema canva\ntable canva.colav2_colav2settings depends on schema canva\ntable canva.colav2_compensationequity depends on schema canva\ntable canva.colav2_visualofferbenefit depends on schema canva\ntable canva.colav2_visualoffergeneralsettings depends on schema canva\ntable canva.company_bulkimport depends on schema canva\ntable canva.company_candidate depends on schema canva\ntable canva.company_company depends on schema canva\ntable canva.company_companydepartment depends on schema canva\ntable canva.company_companyrange depends on schema canva\ntable canva.company_country depends on schema canva\ntable canva.company_ecoheaderconfig depends on schema canva\ntable canva.company_employee depends on schema canva\ntable canva.company_employeev2 depends on schema canva\ntable canva.company_employeev2csvimport depends on schema canva\ntable canva.company_employeev2displaydata depends on schema canva\ntable canva.company_employeev2displaylayout depends on schema canva\ntable canva.company_employeev2optiongrant depends on schema canva\ntable canva.company_employeev2optiongrantcsvimport depends on schema canva\ntable canva.company_employeev2vestingschedule depends on schema canva\ntable canva.company_employeev2vestingschedulecsvimport depends on schema canva\ntable canva.company_employeev2vestingschedulerow depends on schema canva\ntable canva.company_geo depends on schema canva\ntable canva.company_idp depends on schema canva\ntable canva.company_job depends on schema canva\ntable canva.company_jobrole depends on schema canva\ntable canva.company_level depends on schema canva\ntable canva.company_pbeconfig depends on schema canva\ntable canva.company_region depends on schema canva\ntable canva.company_ssosettings depends on schema canva\ntable canva.company_tablerow depends on schema canva\ntable canva.company_tablerow_calculated_from depends on schema canva\ntable canva.company_tablerow_range_calculated_from depends on schema canva\ntable canva.company_team depends on schema canva\ntable canva.csvimport_csvimport depends on schema canva\ntable canva.csvimport_importmodel depends on schema canva\ntable canva.csvtests_country depends on schema canva\ntable canva.csvtests_issue98 depends on schema canva\ntable canva.csvtests_item depends on schema canva\ntable canva.csvtests_organisation depends on schema canva\ntable canva.csvtests_unitofmeasure depends on schema canva\ntable canva.defender_accessattempt depends on schema canva\ntable canva.django_admin_log depends on schema canva\ntable canva.django_content_type depends on schema canva\ntable canva.django_migrations depends on schema canva\ntable canva.django_rest_passwordreset_resetpasswordtoken depends on schema canva\ntable canva.django_session depends on schema canva\ntable canva.django_site depends on schema canva\ntable canva.file_file depends on schema canva\nand 110 other objects (see server log for list)\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n'
2024-01-19 10:57:36,705 (54296/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-01-19 10:57:36,705 (54296/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-01 08:13:09,715 (75756/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-01 08:13:09,715 (75756/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-01 08:21:09,108 (76520/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-01 08:21:09,108 (76520/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-01 08:21:28,987 (76520/MainThread) pgcli.pgexecute ERROR - sql: 'drop schema hero', error: DependentObjectsStillExist('cannot drop schema hero because other objects depend on it\nDETAIL:  table hero.django_migrations depends on schema hero\ntable hero.django_content_type depends on schema hero\ntable hero.auth_permission depends on schema hero\ntable hero.auth_group depends on schema hero\ntable hero.auth_group_permissions depends on schema hero\ntable hero.users_email depends on schema hero\ntable hero.users_user depends on schema hero\ntable hero.users_user_groups depends on schema hero\ntable hero.users_user_user_permissions depends on schema hero\ntable hero.django_admin_log depends on schema hero\ntable hero.merge_integration depends on schema hero\ntable hero.merge_mergeresource depends on schema hero\ntable hero.company_company depends on schema hero\ntable hero.company_employee depends on schema hero\ntable hero.company_companyrange depends on schema hero\ntable hero.company_companydepartment depends on schema hero\ntable hero.company_region depends on schema hero\ntable hero.company_level depends on schema hero\ntable hero.company_job depends on schema hero\ntable hero.company_candidate depends on schema hero\ntable hero.company_geo depends on schema hero\ntable hero.company_country depends on schema hero\ntable hero.ats_ats depends on schema hero\ntable hero.ats_ghcandidate depends on schema hero\ntable hero.ats_ghcustomfield depends on schema hero\ntable hero.ats_ghcustomfieldoption depends on schema hero\ntable hero.ats_ghshowif depends on schema hero\ntable hero.ats_ghcustomfieldgroup depends on schema hero\ntable hero.ats_ghjob depends on schema hero\ntable hero.ats_ghoffer depends on schema hero\ntable hero.ats_atsmappingoptions depends on schema hero\ntable hero.ats_greenhousemapping depends on schema hero\ntable hero.ats_integrationrecord depends on schema hero\ntable hero.approval_chains_approvalchain depends on schema hero\ntable hero.approval_chains_link depends on schema hero\ntable hero.approval_chains_linkapprover depends on schema hero\ntable hero.approval_chains_chainmatcher depends on schema hero\ntable hero.approval_chains_customcriteria depends on schema hero\ntable hero.authtoken_token depends on schema hero\ntable hero.ccp_ccpemployee depends on schema hero\ntable hero.ccp_compcycle depends on schema hero\ntable hero.ccp_wave depends on schema hero\ntable hero.ccp_ccpemployeechangehistory depends on schema hero\ntable hero.ccp_csvimport depends on schema hero\ntable hero.ccp_ccpemployeeactivity depends on schema hero\ntable hero.ccp_ccpemployeeactivity_mentions depends on schema hero\ntable hero.ccp_displaylayout depends on schema hero\ntable hero.ccp_displaydata depends on schema hero\ntable hero.ccp_compelement depends on schema hero\ntable hero.ccp_rewardletter depends on schema hero\ntable hero.ccp_rewardletterimport depends on schema hero\ntable hero.ccp_rewardletterconfig depends on schema hero\ntable hero.ccp_rewardletterarchive depends on schema hero\ntable hero.ccp_computation depends on schema hero\ntable hero.ccp_computation_employees depends on schema hero\ntable hero.ccp_computationchangehistory depends on schema hero\ntable hero.ccp_planninggroup depends on schema hero\ntable hero.ccp_planningrole depends on schema hero\ntable hero.ccp_planningrole_users depends on schema hero\ntable hero.ccp_planningrole_ccp_employees depends on schema hero\ntable hero.ccp_planninggroupchangehistory depends on schema hero\ntable hero.ccp_discretionaryfund depends on schema hero\ntable hero.ccp_csvexport depends on schema hero\ntable hero.ccp_dataoption depends on schema hero\nfunction hero._update_ccp_discretionaryfund_path() depends on schema hero\nfunction hero._add_ccp_discretionaryfund_to_descendant_paths() depends on schema hero\nfunction hero._update_ccp_discretionaryfund_descendant_paths() depends on schema hero\nfunction hero._delete_ccp_discretionaryfund() depends on schema hero\ntable hero.ccp_csvimportemployeepatch depends on schema hero\ntable hero.ccp_ccpdashboardconfig depends on schema hero\ntable hero.ccp_dashboardbadge depends on schema hero\ntable hero.ccp_rewardlettertemplate depends on schema hero\ntable hero.ccp_rewardlettertemplateasset depends on schema hero\nfunction hero._update_ccp_displaylayout_path() depends on schema hero\nfunction hero._add_ccp_displaylayout_to_descendant_paths() depends on schema hero\nfunction hero._update_ccp_displaylayout_descendant_paths() depends on schema hero\ntable hero.ccp_employeecomputation depends on schema hero\ntable hero.ccp_employeeemployeecomputation depends on schema hero\ntable hero.ccp_employeecomputationchangehistory depends on schema hero\ntable hero.colav2_colav2settings depends on schema hero\ntable hero.colav2_colav2culturecontent depends on schema hero\ntable hero.colav2_colav2 depends on schema hero\ntable hero.colav2_colav2compensation depends on schema hero\ntable hero.colav2_compensationequity depends on schema hero\ntable hero.colav2_visualoffergeneralsettings depends on schema hero\ntable hero.colav2_visualofferbenefit depends on schema hero\ntable hero.comp_cycle_eventlog depends on schema hero\ntable hero.comp_cycle_apiresponse depends on schema hero\ntable hero.comp_cycle_apirequest depends on schema hero\ntable hero.comp_cycle_apierror depends on schema hero\ntable hero.comp_cycle_ai_assistant_summary depends on schema hero\ntable hero.ranges_corange depends on schema hero\ntable hero.offers_offer depends on schema hero\ntable hero.offers_offerbenefit depends on schema hero\ntable hero.offers_offerapprovallink depends on schema hero\ntable hero.offers_offerapprover depends on schema hero\ntable hero.offers_offerapprovalchain depends on schema hero\ntable hero.offers_offeractivity depends on schema hero\ntable hero.offers_competingoffer depends on schema hero\ntable hero.offers_offer_associated_users depends on schema hero\nand 57 other objects (see server log for list)\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.')
2024-06-01 08:21:28,991 (76520/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DependentObjectsStillExist: cannot drop schema hero because other objects depend on it\nDETAIL:  table hero.django_migrations depends on schema hero\ntable hero.django_content_type depends on schema hero\ntable hero.auth_permission depends on schema hero\ntable hero.auth_group depends on schema hero\ntable hero.auth_group_permissions depends on schema hero\ntable hero.users_email depends on schema hero\ntable hero.users_user depends on schema hero\ntable hero.users_user_groups depends on schema hero\ntable hero.users_user_user_permissions depends on schema hero\ntable hero.django_admin_log depends on schema hero\ntable hero.merge_integration depends on schema hero\ntable hero.merge_mergeresource depends on schema hero\ntable hero.company_company depends on schema hero\ntable hero.company_employee depends on schema hero\ntable hero.company_companyrange depends on schema hero\ntable hero.company_companydepartment depends on schema hero\ntable hero.company_region depends on schema hero\ntable hero.company_level depends on schema hero\ntable hero.company_job depends on schema hero\ntable hero.company_candidate depends on schema hero\ntable hero.company_geo depends on schema hero\ntable hero.company_country depends on schema hero\ntable hero.ats_ats depends on schema hero\ntable hero.ats_ghcandidate depends on schema hero\ntable hero.ats_ghcustomfield depends on schema hero\ntable hero.ats_ghcustomfieldoption depends on schema hero\ntable hero.ats_ghshowif depends on schema hero\ntable hero.ats_ghcustomfieldgroup depends on schema hero\ntable hero.ats_ghjob depends on schema hero\ntable hero.ats_ghoffer depends on schema hero\ntable hero.ats_atsmappingoptions depends on schema hero\ntable hero.ats_greenhousemapping depends on schema hero\ntable hero.ats_integrationrecord depends on schema hero\ntable hero.approval_chains_approvalchain depends on schema hero\ntable hero.approval_chains_link depends on schema hero\ntable hero.approval_chains_linkapprover depends on schema hero\ntable hero.approval_chains_chainmatcher depends on schema hero\ntable hero.approval_chains_customcriteria depends on schema hero\ntable hero.authtoken_token depends on schema hero\ntable hero.ccp_ccpemployee depends on schema hero\ntable hero.ccp_compcycle depends on schema hero\ntable hero.ccp_wave depends on schema hero\ntable hero.ccp_ccpemployeechangehistory depends on schema hero\ntable hero.ccp_csvimport depends on schema hero\ntable hero.ccp_ccpemployeeactivity depends on schema hero\ntable hero.ccp_ccpemployeeactivity_mentions depends on schema hero\ntable hero.ccp_displaylayout depends on schema hero\ntable hero.ccp_displaydata depends on schema hero\ntable hero.ccp_compelement depends on schema hero\ntable hero.ccp_rewardletter depends on schema hero\ntable hero.ccp_rewardletterimport depends on schema hero\ntable hero.ccp_rewardletterconfig depends on schema hero\ntable hero.ccp_rewardletterarchive depends on schema hero\ntable hero.ccp_computation depends on schema hero\ntable hero.ccp_computation_employees depends on schema hero\ntable hero.ccp_computationchangehistory depends on schema hero\ntable hero.ccp_planninggroup depends on schema hero\ntable hero.ccp_planningrole depends on schema hero\ntable hero.ccp_planningrole_users depends on schema hero\ntable hero.ccp_planningrole_ccp_employees depends on schema hero\ntable hero.ccp_planninggroupchangehistory depends on schema hero\ntable hero.ccp_discretionaryfund depends on schema hero\ntable hero.ccp_csvexport depends on schema hero\ntable hero.ccp_dataoption depends on schema hero\nfunction hero._update_ccp_discretionaryfund_path() depends on schema hero\nfunction hero._add_ccp_discretionaryfund_to_descendant_paths() depends on schema hero\nfunction hero._update_ccp_discretionaryfund_descendant_paths() depends on schema hero\nfunction hero._delete_ccp_discretionaryfund() depends on schema hero\ntable hero.ccp_csvimportemployeepatch depends on schema hero\ntable hero.ccp_ccpdashboardconfig depends on schema hero\ntable hero.ccp_dashboardbadge depends on schema hero\ntable hero.ccp_rewardlettertemplate depends on schema hero\ntable hero.ccp_rewardlettertemplateasset depends on schema hero\nfunction hero._update_ccp_displaylayout_path() depends on schema hero\nfunction hero._add_ccp_displaylayout_to_descendant_paths() depends on schema hero\nfunction hero._update_ccp_displaylayout_descendant_paths() depends on schema hero\ntable hero.ccp_employeecomputation depends on schema hero\ntable hero.ccp_employeeemployeecomputation depends on schema hero\ntable hero.ccp_employeecomputationchangehistory depends on schema hero\ntable hero.colav2_colav2settings depends on schema hero\ntable hero.colav2_colav2culturecontent depends on schema hero\ntable hero.colav2_colav2 depends on schema hero\ntable hero.colav2_colav2compensation depends on schema hero\ntable hero.colav2_compensationequity depends on schema hero\ntable hero.colav2_visualoffergeneralsettings depends on schema hero\ntable hero.colav2_visualofferbenefit depends on schema hero\ntable hero.comp_cycle_eventlog depends on schema hero\ntable hero.comp_cycle_apiresponse depends on schema hero\ntable hero.comp_cycle_apirequest depends on schema hero\ntable hero.comp_cycle_apierror depends on schema hero\ntable hero.comp_cycle_ai_assistant_summary depends on schema hero\ntable hero.ranges_corange depends on schema hero\ntable hero.offers_offer depends on schema hero\ntable hero.offers_offerbenefit depends on schema hero\ntable hero.offers_offerapprovallink depends on schema hero\ntable hero.offers_offerapprover depends on schema hero\ntable hero.offers_offerapprovalchain depends on schema hero\ntable hero.offers_offeractivity depends on schema hero\ntable hero.offers_competingoffer depends on schema hero\ntable hero.offers_offer_associated_users depends on schema hero\nand 57 other objects (see server log for list)\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n'
2024-06-01 08:45:03,181 (79703/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-01 08:45:03,181 (79703/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-01 08:46:11,997 (79703/MainThread) pgcli.pgexecute ERROR - sql: "drop from public.customers_client where schema_name = 'notion'", error: SyntaxError('syntax error at or near "from"\nLINE 1: drop from public.customers_client where schema_name = \'notio...\n             ^')
2024-06-01 08:46:12,000 (79703/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "from"\nLINE 1: drop from public.customers_client where schema_name = \'notio...\n             ^\n'
2024-06-01 08:46:18,121 (79703/MainThread) pgcli.pgexecute ERROR - sql: "drop * from public.customers_client where schema_name = 'notion'", error: SyntaxError('syntax error at or near "*"\nLINE 1: drop * from public.customers_client where schema_name = \'not...\n             ^')
2024-06-01 08:46:18,122 (79703/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "*"\nLINE 1: drop * from public.customers_client where schema_name = \'not...\n             ^\n'
2024-06-01 08:46:34,975 (79703/MainThread) pgcli.pgexecute ERROR - sql: "delete from public.customers_client where schema_name = 'notion'", error: ForeignKeyViolation('update or delete on table "customers_client" violates foreign key constraint "customers_domain_tenant_id_82b7fe24_fk_customers_client_id" on table "customers_domain"\nDETAIL:  Key (id)=(10639) is still referenced from table "customers_domain".')
2024-06-01 08:46:34,976 (79703/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.ForeignKeyViolation: update or delete on table "customers_client" violates foreign key constraint "customers_domain_tenant_id_82b7fe24_fk_customers_client_id" on table "customers_domain"\nDETAIL:  Key (id)=(10639) is still referenced from table "customers_domain".\n'
2024-06-01 08:47:12,794 (79703/MainThread) pgcli.pgexecute ERROR - sql: "delete from public.customers_client where schema_name = 'notion' cascade", error: SyntaxError('syntax error at or near "cascade"\nLINE 1: ...public.customers_client where schema_name = \'notion\' cascade\n                                                                ^')
2024-06-01 08:47:12,795 (79703/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "cascade"\nLINE 1: ...public.customers_client where schema_name = \'notion\' cascade\n                                                                ^\n'
2024-06-01 08:48:04,202 (79703/MainThread) pgcli.pgexecute ERROR - sql: "delete from public.customers_client where schema_name = 'notion'", error: ForeignKeyViolation('update or delete on table "customers_client" violates foreign key constraint "customers_domain_tenant_id_82b7fe24_fk_customers_client_id" on table "customers_domain"\nDETAIL:  Key (id)=(10639) is still referenced from table "customers_domain".')
2024-06-01 08:48:04,203 (79703/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.ForeignKeyViolation: update or delete on table "customers_client" violates foreign key constraint "customers_domain_tenant_id_82b7fe24_fk_customers_client_id" on table "customers_domain"\nDETAIL:  Key (id)=(10639) is still referenced from table "customers_domain".\n'
2024-06-02 20:41:55,458 (61611/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-02 20:41:55,459 (61611/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-02 20:43:44,964 (63361/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-02 20:43:44,964 (63361/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-02 20:44:22,320 (64649/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-02 20:44:22,320 (64649/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-06-03 08:17:45,935 (95229/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-06-03 08:17:45,936 (95229/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-07-25 17:28:52,045 (21492/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-07-25 17:28:52,045 (21492/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-07-25 17:29:00,446 (21492/MainThread) pgcli.pgexecute ERROR - sql: 'select * from standard.*', error: SyntaxError('syntax error at end of input\nLINE 1: select * from standard.*\n                                ^')
2024-07-25 17:29:00,452 (21492/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from standard.*\n                                ^\n'
2024-08-21 14:18:38,138 (68240/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-21 14:18:38,138 (68240/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-21 14:18:38,148 (68240/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "pequity_development" does not exist\n'
2024-08-21 14:18:42,821 (68350/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-21 14:18:42,822 (68350/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-21 14:18:42,827 (68350/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "pequity" does not exist\n'
2024-08-21 14:18:48,128 (68465/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-21 14:18:48,129 (68465/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-21 14:18:48,132 (68465/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "pequity_local" does not exist\n'
2024-08-21 14:20:13,408 (68708/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-21 14:20:13,408 (68708/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-21 14:20:13,414 (68708/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "pequity_local" does not exist\n'
2024-08-21 14:20:35,339 (69259/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-21 14:20:35,339 (69259/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 19:42:20,927 (78412/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 19:42:20,927 (78412/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 19:42:20,929 (78412/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5434" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-08-25 19:42:29,756 (78532/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 19:42:29,756 (78532/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 19:42:29,767 (78532/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-08-25 19:43:35,443 (79285/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 19:43:35,443 (79285/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 19:43:35,451 (79285/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-25 19:47:23,433 (80663/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 19:47:23,433 (80663/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 19:47:23,442 (80663/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-25 20:10:20,294 (84655/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:10:20,295 (84655/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:11:20,389 (84655/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n'
2024-08-25 20:13:14,497 (85700/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:13:14,497 (85700/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:14:13,316 (85700/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n'
2024-08-25 20:17:05,210 (87466/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:17:05,210 (87466/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:18:06,836 (87466/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n'
2024-08-25 20:20:33,048 (88728/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:20:33,049 (88728/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:21:44,778 (88728/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-25 20:22:57,615 (89797/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:22:57,615 (89797/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:22:57,624 (89797/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-25 20:23:41,807 (90129/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:23:41,807 (90129/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:24:21,061 (90778/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:24:21,061 (90778/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:29:41,351 (92628/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:29:41,351 (92628/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:29:41,362 (92628/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 277, in connect\n    if not self.is_virtual_database():\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 189, in is_virtual_database\n    self._is_virtual_database = self.is_protocol_error()\n                                ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 647, in is_protocol_error\n    cur.execute(query)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.DatabaseError: unexpected field count in "D" message\n'
2024-08-25 20:31:06,885 (93209/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:31:06,885 (93209/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:32:21,233 (93944/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:32:21,234 (93944/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:36:22,144 (95070/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:36:22,145 (95070/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:38:38,407 (95811/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:38:38,407 (95811/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:39:44,827 (96312/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:39:44,827 (96312/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:41:17,431 (97018/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:41:17,432 (97018/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:43:16,205 (97731/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:43:16,206 (97731/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:46:48,582 (98719/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:46:48,582 (98719/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:47:05,510 (98719/MainThread) pgcli.main ERROR - sql: 'select * from mastec.users_user;', error: ValueError("invalid literal for int() with base 10: b'REDACTED'")
2024-08-25 20:47:05,511 (98719/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1848, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/cli_helpers/tabular_output/output_formatter.py", line 165, in format_output\n    data = list(data)\n           ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 871, in __iter__\n    row = load(self._pos)\n          ^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 868, in load\n    return self._tx.load_row(pos, self._make_row)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_transform.py", line 326, in load_row\n    record[col] = self._row_loaders[col](val)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/types/numeric.py", line 212, in load\n    return int(data)\n           ^^^^^^^^^\nValueError: invalid literal for int() with base 10: b\'REDACTED\'\n'
2024-08-25 20:52:22,868 (494/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:52:22,870 (494/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:52:26,627 (494/MainThread) pgcli.main ERROR - sql: 'select * from mastec.users_user;', error: ValueError('badly formed hexadecimal UUID string')
2024-08-25 20:52:26,628 (494/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1848, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/cli_helpers/tabular_output/output_formatter.py", line 165, in format_output\n    data = list(data)\n           ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 871, in __iter__\n    row = load(self._pos)\n          ^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 868, in load\n    return self._tx.load_row(pos, self._make_row)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_transform.py", line 326, in load_row\n    record[col] = self._row_loaders[col](val)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/types/uuid.py", line 45, in load\n    return UUID(data.decode())\n           ^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/uuid.py", line 178, in __init__\n    raise ValueError(\'badly formed hexadecimal UUID string\')\nValueError: badly formed hexadecimal UUID string\n'
2024-08-25 20:53:18,698 (1026/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:53:18,698 (1026/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:53:21,588 (1026/MainThread) pgcli.main ERROR - sql: 'select * from mastec.users_user;', error: ValueError('badly formed hexadecimal UUID string')
2024-08-25 20:53:21,590 (1026/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1194, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1848, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/cli_helpers/tabular_output/output_formatter.py", line 165, in format_output\n    data = list(data)\n           ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 871, in __iter__\n    row = load(self._pos)\n          ^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 868, in load\n    return self._tx.load_row(pos, self._make_row)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_transform.py", line 326, in load_row\n    record[col] = self._row_loaders[col](val)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/types/uuid.py", line 45, in load\n    return UUID(data.decode())\n           ^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/uuid.py", line 178, in __init__\n    raise ValueError(\'badly formed hexadecimal UUID string\')\nValueError: badly formed hexadecimal UUID string\n'
2024-08-25 20:54:37,217 (2005/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:54:37,218 (2005/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:55:10,030 (2337/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:55:10,031 (2337/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-25 20:55:52,532 (2576/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-25 20:55:52,533 (2576/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 06:59:24,354 (37993/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 06:59:24,355 (37993/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 06:59:24,379 (37993/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-26 07:09:21,024 (40007/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 07:09:21,024 (40007/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 07:09:21,047 (40007/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-26 07:09:46,294 (40140/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 07:09:46,294 (40140/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 07:09:46,305 (40140/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "::1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-08-26 07:15:34,867 (41434/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 07:15:34,867 (41434/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 07:55:52,953 (47138/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 07:55:52,954 (47138/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-26 07:56:01,842 (47370/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-26 07:56:01,842 (47370/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-28 17:03:19,675 (81532/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-28 17:03:19,676 (81532/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-30 08:38:46,955 (34349/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-30 08:38:46,956 (34349/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-30 10:35:41,622 (45997/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-30 10:35:41,622 (45997/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-30 10:35:42,926 (45997/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "100.99.215.90", port 5434 failed: fe_sendauth: no password supplied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 747, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "100.99.215.90", port 5434 failed: FATAL:  password authentication failed for user "maplesweet"\nconnection to server at "100.99.215.90", port 5434 failed: FATAL:  password authentication failed for user "maplesweet"\n'
2024-08-30 10:35:45,006 (46087/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-30 10:35:45,006 (46087/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-30 10:39:37,424 (46087/MainThread) pgcli.pgexecute ERROR - sql: 'select * from public.django_session order id desc', error: SyntaxError('syntax error at or near "id"\nLINE 1: select * from public.django_session order id desc\n                                                  ^')
2024-08-30 10:39:37,433 (46087/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "id"\nLINE 1: select * from public.django_session order id desc\n                                                  ^\n'
2024-08-30 10:43:25,831 (46983/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-30 10:43:25,831 (46983/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:09:57,129 (44116/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:09:57,129 (44116/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:10:22,287 (44553/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:10:22,287 (44553/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:11:44,586 (45762/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:11:44,586 (45762/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:11:57,949 (46049/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:11:57,949 (46049/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:15:42,070 (47812/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:15:42,070 (47812/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:15:59,436 (48101/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:15:59,436 (48101/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 08:16:38,523 (48862/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 08:16:38,523 (48862/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 14:55:39,500 (81525/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 14:55:39,501 (81525/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 14:55:57,412 (81525/MainThread) pgcli.pgexecute ERROR - sql: 'drop table organizations', error: DependentObjectsStillExist('cannot drop table organizations because other objects depend on it\nDETAIL:  constraint users_organization_id_fkey on table users depends on table organizations\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.')
2024-08-31 14:55:57,421 (81525/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DependentObjectsStillExist: cannot drop table organizations because other objects depend on it\nDETAIL:  constraint users_organization_id_fkey on table users depends on table organizations\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n'
2024-08-31 14:57:11,369 (83083/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 14:57:11,369 (83083/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 14:57:23,077 (83574/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 14:57:23,078 (83574/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 14:59:02,271 (85459/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 14:59:02,271 (85459/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-08-31 14:59:24,713 (85930/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-08-31 14:59:24,713 (85930/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 07:32:16,579 (52484/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 07:32:16,580 (52484/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 19:57:50,448 (3918/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 19:57:50,449 (3918/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 19:57:50,589 (3918/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 20:01:31,286 (4652/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:01:31,286 (4652/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:01:48,910 (4652/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 20:02:54,024 (5400/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:02:54,024 (5400/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:03:09,222 (5400/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 20:06:18,630 (6390/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:06:18,630 (6390/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:08:28,651 (6390/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 20:23:17,037 (9873/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:23:17,038 (9873/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:25:27,060 (9873/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 20:29:48,144 (11872/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:29:48,145 (11872/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:31:58,168 (11872/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 20:37:11,696 (13723/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:37:11,697 (13723/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:37:23,523 (13723/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 20:39:27,040 (14574/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:39:27,040 (14574/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:41:37,063 (14574/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 20:43:55,254 (15580/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:43:55,254 (15580/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:45:26,121 (15580/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 20:57:23,059 (18355/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:57:23,059 (18355/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:57:23,069 (18355/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-09-01 20:57:57,564 (18816/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:57:57,564 (18816/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:57:57,574 (18816/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-09-01 20:58:15,497 (18968/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:58:15,497 (18968/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 20:58:15,506 (18968/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-09-01 20:59:51,154 (19414/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 20:59:51,154 (19414/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:02:01,176 (19414/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 21:03:45,152 (20414/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:03:45,152 (20414/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:05:34,350 (20414/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 21:06:06,048 (21252/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:06:06,048 (21252/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:07:54,464 (21252/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 21:12:11,967 (22542/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:12:11,967 (22542/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:14:21,989 (22542/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 21:15:21,898 (23444/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:15:21,899 (23444/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:16:13,932 (23444/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-01 21:19:10,900 (24825/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:19:10,900 (24825/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:21:20,925 (24825/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 21:22:09,120 (26387/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:22:09,120 (26387/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:24:19,141 (26387/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.errors.ConnectionTimeout: connection timeout expired\n'
2024-09-01 21:25:04,542 (27231/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-01 21:25:04,543 (27231/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-01 21:25:32,591 (27231/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 06:55:17,060 (30161/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 06:55:17,060 (30161/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 06:58:49,797 (31167/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 06:58:49,798 (31167/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 06:59:03,753 (31167/MainThread) pgcli.pgexecute ERROR - sql: 'select * from schema_migrations', error: UndefinedTable('relation "schema_migrations" does not exist\nLINE 1: select * from schema_migrations\n                      ^')
2024-09-02 06:59:03,758 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "schema_migrations" does not exist\nLINE 1: select * from schema_migrations\n                      ^\n'
2024-09-02 06:59:49,081 (31167/MainThread) pgcli.pgexecute ERROR - sql: 'select * from users', error: OperationalError('consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.')
2024-09-02 06:59:49,081 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 06:59:49,082 (31167/MainThread) pgcli.main ERROR - sql: 'select * from users;', error: OperationalError('consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.')
2024-09-02 06:59:49,083 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: consuming input failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 06:59:50,856 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:50,857 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:50,857 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:50,858 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:52,829 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:52,830 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:52,830 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:52,831 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:55,608 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:55,608 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:55,608 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:55,609 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:56,261 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:56,261 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 06:59:56,261 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 06:59:56,262 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:01,498 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:01,499 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:01,499 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:01,500 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:02,153 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:02,154 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:02,154 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:02,155 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:05,600 (31167/MainThread) pgcli.pgexecute ERROR - sql: 'ecit()', error: OperationalError('the connection is closed')
2024-09-02 07:00:05,600 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:05,600 (31167/MainThread) pgcli.main ERROR - sql: 'ecit()', error: OperationalError('the connection is closed')
2024-09-02 07:00:05,601 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:07,125 (31167/MainThread) pgcli.pgexecute ERROR - sql: 'exit()', error: OperationalError('the connection is closed')
2024-09-02 07:00:07,126 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:07,126 (31167/MainThread) pgcli.main ERROR - sql: 'exit()', error: OperationalError('the connection is closed')
2024-09-02 07:00:07,126 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:16,691 (31167/MainThread) pgcli.pgexecute ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:16,692 (31167/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:00:16,692 (31167/MainThread) pgcli.main ERROR - sql: '\\q', error: OperationalError('the connection is closed')
2024-09-02 07:00:16,693 (31167/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 382, in run\n    cur = self.conn.cursor()\n          ^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 852, in cursor\n    self._check_connection_ok()\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 485, in _check_connection_ok\n    raise e.OperationalError("the connection is closed")\npsycopg.OperationalError: the connection is closed\n'
2024-09-02 07:12:08,775 (34130/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:12:08,775 (34130/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:15:12,548 (35282/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:15:12,548 (35282/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:19:26,513 (36589/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:19:26,513 (36589/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:20:06,867 (36589/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 07:24:12,390 (37749/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:24:12,390 (37749/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:25:54,352 (37749/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 07:31:31,327 (39565/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:31:31,327 (39565/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:32:14,327 (39565/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 07:34:33,510 (40904/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:34:33,510 (40904/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:34:33,520 (40904/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: could not receive data from server: Connection refused\n'
2024-09-02 07:34:46,085 (41093/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 07:34:46,086 (41093/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 07:35:27,857 (41093/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5434 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2024-09-02 08:03:16,673 (47733/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-02 08:03:16,674 (47733/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-02 08:06:05,709 (47733/MainThread) pgcli.pgexecute ERROR - sql: 'rollback', error: OperationalError('sending query failed: invalid frontend message type 1\nanother command is already in progress')
2024-09-02 08:06:05,719 (47733/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 988, in run_cli\n    self.handle_watch_command(text)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1030, in handle_watch_command\n    query = self.execute_command(text)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 389, in run\n    response = pgspecial.execute(cur, sql)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgspecial/main.py", line 114, in execute\n    return special_cmd.handler()\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 325, in quit\n    raise PgCliQuitError\npgcli.main.PgCliQuitError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: invalid frontend message type 1\nanother command is already in progress\n'
2024-09-17 06:53:12,115 (3555/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-17 06:53:12,116 (3555/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-17 06:54:45,011 (3807/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-17 06:54:45,011 (3807/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-17 18:23:25,383 (32444/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-17 18:23:25,384 (32444/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-17 18:25:19,708 (32444/MainThread) pgcli.pgexecute ERROR - sql: "COPY(select * from fervoenergy.company_employeev2 where eid in ('271', '272', '273', '274', '275', '276', '277', '278', '279', '289')) to '~/Desktop/fervo_employees.csv' WITH CSV HEADER", error: FeatureNotSupported("COPY to a file is not supported\nHINT:  Anyone can COPY to stdout or from stdin. psql's \\copy command also works for anyone.")
2024-09-17 18:25:19,721 (32444/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: COPY to a file is not supported\nHINT:  Anyone can COPY to stdout or from stdin. psql\'s \\copy command also works for anyone.\n'
2024-09-24 17:03:18,243 (62784/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-24 17:03:18,244 (62784/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-26 18:10:06,823 (35909/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-26 18:10:06,824 (35909/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-26 18:13:22,060 (36356/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-26 18:13:22,061 (36356/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-26 18:22:21,046 (37390/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-26 18:22:21,047 (37390/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-09-26 18:57:27,914 (41675/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-09-26 18:57:27,915 (41675/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-10 11:57:01,579 (21855/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-10 11:57:01,580 (21855/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-10 11:57:01,685 (21855/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 728, in connect\n    attempts = conninfo_attempts(params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 45, in conninfo_attempts\n    raise e.OperationalError(str(last_exc))\npsycopg.OperationalError: [Errno 8] nodename nor servname provided, or not known\n'
2024-10-10 12:00:14,101 (23856/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-10 12:00:14,101 (23856/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-10 12:00:14,131 (23856/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 728, in connect\n    attempts = conninfo_attempts(params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 45, in conninfo_attempts\n    raise e.OperationalError(str(last_exc))\npsycopg.OperationalError: [Errno 8] nodename nor servname provided, or not known\n'
2024-10-10 12:00:20,052 (24250/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-10 12:00:20,053 (24250/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-10 12:00:20,057 (24250/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 728, in connect\n    attempts = conninfo_attempts(params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 45, in conninfo_attempts\n    raise e.OperationalError(str(last_exc))\npsycopg.OperationalError: [Errno 8] nodename nor servname provided, or not known\n'
2024-10-10 12:01:29,888 (25501/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-10 12:01:29,889 (25501/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-10 12:01:40,939 (25501/MainThread) pgcli.pgexecute ERROR - sql: 'select * from instacart.*', error: SyntaxError('syntax error at end of input\nLINE 1: select * from instacart.*\n                                 ^')
2024-10-10 12:01:40,950 (25501/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from instacart.*\n                                 ^\n'
2024-10-10 12:03:53,571 (25501/MainThread) pgcli.pgexecute ERROR - sql: 'select * from instacart.auth_user_groups', error: UndefinedTable('relation "instacart.auth_user_groups" does not exist\nLINE 1: select * from instacart.auth_user_groups\n                      ^')
2024-10-10 12:03:53,573 (25501/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "instacart.auth_user_groups" does not exist\nLINE 1: select * from instacart.auth_user_groups\n                      ^\n'
2024-10-10 14:04:00,218 (98844/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-10 14:04:00,219 (98844/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-14 12:36:13,472 (74089/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-14 12:36:13,473 (74089/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-14 14:18:15,784 (85282/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-14 14:18:15,785 (85282/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-20 16:51:07,892 (14992/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-20 16:51:07,893 (14992/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-20 16:53:02,099 (14992/MainThread) pgcli.pgexecute ERROR - sql: 'select * from company_companyjob', error: UndefinedTable('relation "company_companyjob" does not exist\nLINE 1: select * from company_companyjob\n                      ^')
2025-01-20 16:53:02,109 (14992/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "company_companyjob" does not exist\nLINE 1: select * from company_companyjob\n                      ^\n'
2025-01-20 16:53:09,654 (14992/MainThread) pgcli.pgexecute ERROR - sql: 'select * from company_companyjob', error: UndefinedTable('relation "company_companyjob" does not exist\nLINE 1: select * from company_companyjob\n                      ^')
2025-01-20 16:53:09,655 (14992/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "company_companyjob" does not exist\nLINE 1: select * from company_companyjob\n                      ^\n'
2025-01-21 20:00:20,513 (1908/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-21 20:00:20,514 (1908/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-01-21 20:00:26,663 (1908/MainThread) pgcli.pgexecute ERROR - sql: 'select * from company_region', error: UndefinedTable('relation "company_region" does not exist\nLINE 1: select * from company_region\n                      ^')
2025-01-21 20:00:26,670 (1908/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "company_region" does not exist\nLINE 1: select * from company_region\n                      ^\n'
2025-02-19 12:42:46,961 (83442/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-19 12:42:46,962 (83442/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-19 12:43:00,759 (83442/MainThread) pgcli.pgexecute ERROR - sql: 'select * from ezcater.*', error: SyntaxError('syntax error at end of input\nLINE 1: select * from ezcater.*\n                               ^')
2025-02-19 12:43:00,773 (83442/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from ezcater.*\n                               ^\n'
2025-02-20 06:26:25,802 (50846/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-20 06:26:25,803 (50846/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-20 06:31:45,779 (50846/MainThread) pgcli.pgexecute ERROR - sql: "DO $$\nDECLARE\n    rec RECORD;\n    query TEXT;\n    result INTEGER;\nBEGIN\n    FOR rec IN\n        SELECT n.nspname AS schema_name\n        FROM pg_catalog.pg_namespace n\n        JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid\n        WHERE c.relname = 'ranges_corange'\n          AND c.relkind = 'r'  -- Only include tables\n          AND n.nspname NOT IN ('pg_catalog', 'information_schema')\n    LOOP\n        query := FORMAT('SELECT COUNT(*) FROM %I.ranges_corange WHERE geo_id IS NULL;', rec.schema_name);\n        EXECUTE query INTO result;\n        RAISE NOTICE 'Schema: %, NULL geo_id Count: %', rec.schema_name, result;\n    END LOOP;\nEND $$", error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress')
2025-02-20 06:31:45,788 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\n'
2025-02-20 06:31:51,180 (50846/MainThread) pgcli.pgexecute ERROR - sql: "DO $$\nDECLARE\n    rec RECORD;\n    query TEXT;\n    result INTEGER;\nBEGIN\n    FOR rec IN\n        SELECT n.nspname AS schema_name\n        FROM pg_catalog.pg_namespace n\n        JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid\n        WHERE c.relname = 'ranges_corange'\n          AND c.relkind = 'r'  -- Only include tables\n          AND n.nspname NOT IN ('pg_catalog', 'information_schema')\n    LOOP\n        query := FORMAT('SELECT COUNT(*) FROM %I.ranges_corange WHERE geo_id IS NULL;', rec.schema_name);\n        EXECUTE query INTO result;\n        RAISE NOTICE 'Schema: %, NULL geo_id Count: %', rec.schema_name, result;\n    END LOOP;\nEND $$", error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:31:51,182 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:32:39,518 (50846/MainThread) pgcli.pgexecute ERROR - sql: "DO $$\nDECLARE\n    rec RECORD;\n    query TEXT;\n    result INTEGER;\nBEGIN\n    FOR rec IN\n        SELECT n.nspname AS schema_name\n        FROM pg_catalog.pg_namespace n\n        JOIN pg_catalog.pg_class c ON c.relnamespace = n.oid\n        WHERE c.relname = 'ranges_corange'\n          AND c.relkind = 'r'  -- Only include tables\n          AND n.nspname NOT IN ('pg_catalog', 'information_schema')\n    LOOP\n        query := FORMAT('SELECT COUNT(*) FROM %I.ranges_corange WHERE geo_id IS NULL;', rec.schema_name);\n        EXECUTE query INTO result;\n        RAISE NOTICE 'Schema: %, NULL geo_id Count: %', rec.schema_name, result;\n    END LOOP;\nEND $$", error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:32:39,519 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:32:51,382 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'rollback', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:32:51,392 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 988, in run_cli\n    self.handle_watch_command(text)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1030, in handle_watch_command\n    query = self.execute_command(text)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 389, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgspecial/main.py", line 114, in execute\n    return special_cmd.handler()\n           ~~~~~~~~~~~~~~~~~~~^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 325, in quit\n    raise PgCliQuitError\npgcli.main.PgCliQuitError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:32:54,836 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'rollback', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:32:54,838 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 988, in run_cli\n    self.handle_watch_command(text)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1030, in handle_watch_command\n    query = self.execute_command(text)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 389, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgspecial/main.py", line 114, in execute\n    return special_cmd.handler()\n           ~~~~~~~~~~~~~~~~~~~^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 325, in quit\n    raise PgCliQuitError\npgcli.main.PgCliQuitError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:32:56,768 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'rollback', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:32:56,770 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 988, in run_cli\n    self.handle_watch_command(text)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1030, in handle_watch_command\n    query = self.execute_command(text)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 389, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgspecial/main.py", line 114, in execute\n    return special_cmd.handler()\n           ~~~~~~~~~~~~~~~~~~~^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 325, in quit\n    raise PgCliQuitError\npgcli.main.PgCliQuitError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:32:58,478 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'exit()', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:32:58,479 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:33:05,900 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'exit()', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:33:05,902 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:33:11,033 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'rollback', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:33:11,036 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 988, in run_cli\n    self.handle_watch_command(text)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1030, in handle_watch_command\n    query = self.execute_command(text)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 833, in execute_command\n    output, query = self._evaluate_command(text)\n                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 1164, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n                                                                 ^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 389, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgspecial/main.py", line 114, in execute\n    return special_cmd.handler()\n           ~~~~~~~~~~~~~~~~~~~^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 325, in quit\n    raise PgCliQuitError\npgcli.main.PgCliQuitError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:33:34,338 (50846/MainThread) pgcli.pgexecute ERROR - sql: 'select count(*) from ezcater.ranges_corange where geo_id = NULL', error: OperationalError('sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress')
2025-02-20 06:33:34,340 (50846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.OperationalError: sending query failed: canceling statement due to user request\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\nanother command is already in progress\n'
2025-02-20 06:34:01,624 (51889/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-20 06:34:01,624 (51889/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-20 07:16:19,833 (59071/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-20 07:16:19,834 (59071/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-20 07:16:47,384 (59071/MainThread) pgcli.pgexecute ERROR - sql: 'select count(*) from maymobility.ranges_coregion', error: UndefinedTable('relation "maymobility.ranges_coregion" does not exist\nLINE 1: select count(*) from maymobility.ranges_coregion\n                             ^')
2025-02-20 07:16:47,395 (59071/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "maymobility.ranges_coregion" does not exist\nLINE 1: select count(*) from maymobility.ranges_coregion\n                             ^\n'
2025-02-25 06:59:55,234 (72244/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-25 06:59:55,235 (72244/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-25 07:00:16,913 (72244/MainThread) pgcli.pgexecute ERROR - sql: 'TRUNCATE instacart.ats_ghcustomfield', error: FeatureNotSupported('cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "approval_chains_customcriteria" references "ats_ghcustomfield".\nHINT:  Truncate table "approval_chains_customcriteria" at the same time, or use TRUNCATE ... CASCADE.')
2025-02-25 07:00:16,928 (72244/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "approval_chains_customcriteria" references "ats_ghcustomfield".\nHINT:  Truncate table "approval_chains_customcriteria" at the same time, or use TRUNCATE ... CASCADE.\n'
2025-02-25 07:00:58,259 (72464/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-25 07:00:58,259 (72464/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
